name: Deploy to Heroku

on:
  pull_request:
    branches:
      - deploy
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# Chỉ deploy khi có PR từ develop vào deploy

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'deploy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: '.'
          usedocker: false
